// <auto-generated />
using CustomerAPI.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CustomerAPI.DataAccess.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20220124193325_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CustomerAPI.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "No21,Galle Rd, Colombo",
                            CustomerName = "Amal",
                            Email = "amal@abc.com",
                            Phone = 775896321
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "No35,Temple Rd, Nugegoda",
                            CustomerName = "Kamal",
                            Email = "kamal@abc.com",
                            Phone = 775896321
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "No48,Galle Rd, Dehiwala",
                            CustomerName = "Saman",
                            Email = "saman@abc.com",
                            Phone = 775896321
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
